/**
 * Generate application timeline based on intake month
 */
export function generateTimeline(intake) {
  const now = new Date();
  const currentYear = now.getFullYear();

  if (intake === 'Sep') {
    return [
      {
        step: 1,
        title: 'Research & Shortlist',
        description: 'Shortlist 8–10 universities based on profile fit, ranking, and budget',
        icon: '🔍',
        color: 'bg-blue-500',
        months: 'April – May',
        dueDate: `May ${currentYear}`,
        status: 'prep',
      },
      {
        step: 2,
        title: 'Take IELTS / TOEFL',
        description: 'Book and appear for English language proficiency test. Target 6.5+ for IELTS',
        icon: '🗣️',
        color: 'bg-purple-500',
        months: 'May – June',
        dueDate: `June ${currentYear}`,
        status: 'prep',
      },
      {
        step: 3,
        title: 'Take GRE / GMAT',
        description: 'Appear for standardized tests if required. GRE Target: 315+',
        icon: '📝',
        color: 'bg-indigo-500',
        months: 'June – July',
        dueDate: `July ${currentYear}`,
        status: 'prep',
      },
      {
        step: 4,
        title: 'Prepare Documents',
        description: 'Write SOP, gather LOR, get transcripts, organize financial documents',
        icon: '📄',
        color: 'bg-teal-500',
        months: 'July – August',
        dueDate: `August ${currentYear}`,
        status: 'apply',
      },
      {
        step: 5,
        title: 'Submit Applications',
        description: 'Apply to all shortlisted universities before their rolling deadlines',
        icon: '📤',
        color: 'bg-green-500',
        months: 'September – November',
        dueDate: `November ${currentYear}`,
        status: 'apply',
      },
      {
        step: 6,
        title: 'Receive Offer Letters',
        description: 'Decisions expected. Accept your top choice and pay the deposit',
        icon: '🎉',
        color: 'bg-yellow-500',
        months: 'December – February',
        dueDate: `February ${currentYear + 1}`,
        status: 'offer',
      },
      {
        step: 7,
        title: 'Apply for Education Loan',
        description: 'Submit loan application with offer letter. Process takes 4–8 weeks',
        icon: '🏦',
        color: 'bg-orange-500',
        months: 'February – March',
        dueDate: `March ${currentYear + 1}`,
        status: 'finance',
      },
      {
        step: 8,
        title: 'Apply for Student Visa',
        description: 'Submit visa application with all documents. Biometrics and interview if needed',
        icon: '🛂',
        color: 'bg-red-500',
        months: 'April – June',
        dueDate: `June ${currentYear + 1}`,
        status: 'visa',
      },
      {
        step: 9,
        title: 'Book Accommodation & Flights',
        description: 'Secure on-campus or off-campus housing. Book flights 6–8 weeks early',
        icon: '✈️',
        color: 'bg-cyan-500',
        months: 'June – August',
        dueDate: `August ${currentYear + 1}`,
        status: 'travel',
      },
      {
        step: 10,
        title: 'Depart & Arrive',
        description: 'Travel to your destination country and begin your education journey!',
        icon: '🌍',
        color: 'bg-emerald-500',
        months: 'August – September',
        dueDate: `September ${currentYear + 1}`,
        status: 'travel',
      },
    ];
  } else {
    // January intake
    return [
      {
        step: 1,
        title: 'Research & Shortlist',
        description: 'Shortlist 8–10 universities based on profile fit, ranking, and budget',
        icon: '🔍',
        color: 'bg-blue-500',
        months: 'January – February',
        dueDate: `February ${currentYear}`,
        status: 'prep',
      },
      {
        step: 2,
        title: 'Take IELTS / TOEFL',
        description: 'Book and appear for English language proficiency test. Target 6.5+ for IELTS',
        icon: '🗣️',
        color: 'bg-purple-500',
        months: 'February – March',
        dueDate: `March ${currentYear}`,
        status: 'prep',
      },
      {
        step: 3,
        title: 'Take GRE / GMAT',
        description: 'Appear for standardized tests if required. GRE Target: 315+',
        icon: '📝',
        color: 'bg-indigo-500',
        months: 'March – April',
        dueDate: `April ${currentYear}`,
        status: 'prep',
      },
      {
        step: 4,
        title: 'Prepare Documents',
        description: 'Write SOP, gather LOR, get transcripts, organize financial documents',
        icon: '📄',
        color: 'bg-teal-500',
        months: 'April – May',
        dueDate: `May ${currentYear}`,
        status: 'apply',
      },
      {
        step: 5,
        title: 'Submit Applications',
        description: 'Apply to all shortlisted universities before their rolling deadlines',
        icon: '📤',
        color: 'bg-green-500',
        months: 'May – July',
        dueDate: `July ${currentYear}`,
        status: 'apply',
      },
      {
        step: 6,
        title: 'Receive Offer Letters',
        description: 'Decisions expected. Accept your top choice and pay the deposit',
        icon: '🎉',
        color: 'bg-yellow-500',
        months: 'August – September',
        dueDate: `September ${currentYear}`,
        status: 'offer',
      },
      {
        step: 7,
        title: 'Apply for Education Loan',
        description: 'Submit loan application with offer letter. Process takes 4–8 weeks',
        icon: '🏦',
        color: 'bg-orange-500',
        months: 'September – October',
        dueDate: `October ${currentYear}`,
        status: 'finance',
      },
      {
        step: 8,
        title: 'Apply for Student Visa',
        description: 'Submit visa application with all documents. Biometrics and interview if needed',
        icon: '🛂',
        color: 'bg-red-500',
        months: 'October – November',
        dueDate: `November ${currentYear}`,
        status: 'visa',
      },
      {
        step: 9,
        title: 'Book Accommodation & Flights',
        description: 'Secure on-campus or off-campus housing. Book flights 6–8 weeks early',
        icon: '✈️',
        color: 'bg-cyan-500',
        months: 'November – December',
        dueDate: `December ${currentYear}`,
        status: 'travel',
      },
      {
        step: 10,
        title: 'Depart & Arrive',
        description: 'Travel to your destination country and begin your education journey!',
        icon: '🌍',
        color: 'bg-emerald-500',
        months: 'December – January',
        dueDate: `January ${currentYear + 1}`,
        status: 'travel',
      },
    ];
  }
}
